function channelIndexCheck(this, index)
%SPECIMEN::CHANNELINDEXCHECK ...
%   ...

upperbound = length(this.Channels);
assert(all(and(index > 0, index <= upperbound)), ...
       sprintf(['!! %d is not a valid channel index. ', ...
                '(0 < index <= %d)'], index, upperbound))

end

